version: '3.8'

services:
  infinitetalk-api:
    image: statsmind/infinitetalk
    container_name: infinitetalk-api
    ports:
      - "18001:8000"
    volumes:
      - /opt/infinitetalk/weights:/app/weights
      - /opt/indextts/uploads:/app/uploads
      - /opt/indextts/outputs:/app/results
      - /opt/infinitetalk/temp:/app/temp
      - ./api/api_main.py:/app/api/api_main.py
    environment:
      - CKPT_DIR=/app/weights/Wan2.1-I2V-14B-480P
      - WAV2VEC_DIR=/app/weights/chinese-wav2vec2-base
      - INFINITETALK_DIR=/app/weights/InfiniteTalk/single/infinitetalk.safetensors
      - QUANT_DIR=/app/weights/InfiniteTalk/quant_models/infinitetalk_single_fp8.safetensors
      - QUANT=fp8
      - NUM_PERSISTENT_PARAM_IN_DIT=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
